# =========================================
# config.toml — ECG App 設定檔（含中文註解）
# 讀取位置：專案根目錄 /config.toml
# 注意：同一段落內（根層、[plot]、[filter]）每個鍵只能出現一次
# =========================================

# ---------- 裝置 / 一般設定 ----------
sampling_rate = 1000            # 取樣率(Hz)。BITalino 常用 1000；若改成 100、250 也可，但須與裝置一致
analog_channels = [1]           # 使用的類比通道索引（以 A1=0, A2=1, A3=2, ... 為準）
                                # 例：ECG 接在 A2 → 設為 [1]；若同時讀多通道可設如 [1, 2]
preferred_mac = ""              # （選用）BLE 自動連線時優先使用的 MAC（例："98:D3:31:xx:xx:xx"）
                                # 留空表示不指定，會由自動掃描決定（需安裝 bleak）
address = ""                  # （選用）有線/指定位址（如 COM port "COM5" 或特定藍牙位址）。通常留空即可
# address = "COM16"             # CUST 8F 研究室 PC
# address = "COM5"              # HOME Book Room PC
# address = "COM9"              # Sports PC

# ---------- 繪圖 / 展示 ----------
[plot]
seconds = 10                    # 畫面時間窗（秒），滑動顯示最近 N 秒資料
chunk = 100                     # 單批讀取/處理樣本數（與裝置 read(chunk) 對應）。1000Hz 時 100=每 0.1 秒更新
gain  = 1.5                     # 顯示增益（僅影響波形高低視覺，不改變數據值）
ecg_col = -1                    # 接收數據欄位 
mode    = "sweep"               # ← 這版預設就是 sweep；想看舊式滑動窗就改 "sliding"
# direction = "rtl"             # 只有在 mode="sliding" 才會用到；sweep 一律左→右
y_padding = 0.25                # 建議值：0.15~0.35；數值越大，上下留白越多。

# ---------- 濾波（即時、串流友善） ----------
[filter]
enable = true                   # 是否啟用濾波；教學時可切換 true/false 對比原始與濾波後波形
band = [0.5, 25.0]              # 帶通頻帶(Hz)：0.5~25 可去除基線漂移與高頻肌電雜訊
notch = 60.0                    # 工頻陷波(Hz)：台灣 60；若干擾不明顯可改 0 停用（0=不做陷波）
order = 4                       # Butterworth 階數（2~4 常見；更陡可 6，但即時延遲與響應會變）
q = 30.0                        # 陷波 Q 值（20~50 常用；數值越大帶寬越窄）


[detector]        # 用于可视化
slope_k = 4.0
pre_lock_ms = 8.0
post_lock_ms = 70.0
tail_ms = 200.0
amp_abs_gate = 250.0
k_mad_height = 2.8
env_ms = 100                # 120 80 100–120 ms：QRS 能量包絡的平滑常數
search_ms = 60              # 在能量峰附近 ±60–80 ms 搜 R apex
refractory_ms = 240         # 不應期
vis_lag_ms = 0              # 紅點視覺補償，可設 -10 ~ -20 向左微調，向左提前0~20 作細微補償（正值=向右一點）
                            # search_half 從 6 調到 8 也可以（在 _prune_rwin_and_update_scatter 裡）
min_env = 0.0      # 先關掉；若雜訊多再慢慢加
min_peak = 0.0     # 同上


[detector_rr]
slope_k = 2.8
k_mad_height = 2.0
amp_abs_gate = 100.0
refractory_ms = 250.0
pre_lock_ms = 15.0
post_lock_ms = 100.0
tail_ms = 300.0

# （選擇）紅點顯示獨立參數
[detector_vis]
refractory_ms = 240
slope_k       = 4.0
k_mad_height  = 2.8
amp_abs_gate  = 250
vis_lag_ms    = 0

[subject_defaults]
# 可選：提供起始號碼的「種子」，例如希望從 RR0200 開始
seed_counter = 8000          # 選填；只會在 .subject_last_id.txt 不存在時生效
id = "AUTO"
name = ""
age  = 0
sex  = "U"   # 可填 "M" 或 "F"
lead = "Lead II (R-arm +, L-arm -, right leg ref.)"
posture = "Quiet Sitting"
notes = ""

[rr]
warmup_sec    = 30.0        # 暖機秒數
warmup_beats  = 30          # 暖機 RR 筆數
warmup_either = true        # true=擇一達成；false=兩者都達成才開始收錄

[battery]
enable = true          # 顯示電量監測
poll_s = 15            # 幾秒查一次
low_pct = 20           # 低電量門檻（狀態列橘色）
critical_pct = 10      # 極低門檻（狀態列紅色與提示）

# 原始 battery 數值的線性映射（不同批次可微調）
raw_min = 511          # 低電（約 0~1%）
raw_max = 645          # 滿電（約 99%）
set_device_threshold_pct = 10   # 告知板子在 ~10% 時點紅燈（可選）

[ui]
window_title = "ECG 訊號擷取、濾波、演算與應用教學系統（教學版）"
font_family  = "Microsoft JhengHei UI"
font_size    = 11                    # 全域預設字型大小

ecg_width  = 1280
ecg_height = 400
# 或者只給比例：
ecg_aspect = 3.2     # width / height；若設定此值，可用它來算 height


# 即時心跳（建議：藍色／不粗體）
rt_hr_color = "#2962FF"
rt_hr_size  = 16
rt_hr_bold  = false

# 穩定心跳（建議：紅色／粗體）
stable_hr_color = "#D32F2F"
stable_hr_size  = 20
stable_hr_bold  = true

# 狀態列與工具列
status_text_color   = "#616161"
toolbar_button_bold = true

# pyqtgraph 軸標題（選配）
plot_label_color = "#90A4AE"
axis_label_size  = "12pt"


# ====== 教學備註 ======
# 1) 若未安裝 scipy，程式會自動改用內建「簡化濾波」（仍可即時運作）。
# 2) 若波形不像 ECG，請確認：
#    - 電極貼附位置與導線擺放
#    - analog_channels 是否對應你的實際接線（A1=0, A2=1, ...）
#    - preferred_mac / address 是否需要（若使用自動連線需安裝 bleak、pyserial）
# 3) notch 建議先依環境實測決定是否開啟；優先改善接地與布線，再依需要開陷波。
# 4) 本軟體用於研究/教學，不屬於醫療診斷。

