# =========================================
# config.toml — ECG App 設定檔（含中文註解）
# 讀取位置：專案根目錄 /config.toml
# 注意：同一段落內（根層、[plot]、[filter]、[ui]…）每個鍵只能出現一次
# =========================================

# ---------- 裝置 / 一般設定 ----------
sampling_rate   = 1000          # 取樣率(Hz)。BITalino 常用 1000；改 100/250 亦可（須與裝置一致）
analog_channels = [1]           # 類比通道索引（A1=0, A2=1, A3=2, …）。例：ECG 接 A2 → [1]
preferred_mac   = ""            # （選用）BLE 優先 MAC，例如 "98:D3:31:xx:xx:xx"（需 bleak）
address         = ""            # （選用）固定位址（如 "COM11"）；通常留空讓程式自動解析

# ---------- 繪圖 / 展示 ----------
[plot]
seconds     = 10                # 視窗時間長度（秒），只顯示最近 N 秒
chunk       = 100               # 單批處理樣本數（1000Hz 時 100=0.1秒更新一次）
gain        = 1.5               # 顯示增益（只影響視覺，不改變數據）
ecg_col     = -1                # 取資料的欄位（-1=最後一欄）
sweep       = false             # 專業心電圖滑動窗：false=固定 10 秒窗、由左→右更新；true=掃描翻頁
direction   = "ltr"             # 滑動窗方向：一律左→右（ltr）
y_padding   = 0.25              # 上下留白（0.15~0.35 建議值）

# ---------- 濾波（即時、串流友善） ----------
[filter]
enable = true                   # 濾波開關（教學時可切換比較）
band   = [0.5, 25.0]            # 帶通頻帶(Hz)；去漂移/高頻肌電
notch  = 60.0                   # 工頻陷波(Hz)。台灣/美國 60；歐洲 50。0=停用
order  = 4                      # Butterworth 階數（2~4 常見）
q      = 30.0                   # 陷波 Q 值（帶寬）

# ---------- RR 擷取的暖機條件（可選） ----------
[rr]
warmup_sec    = 30.0            # 暖機秒數
warmup_beats  = 30              # 暖機筆數
warmup_either = true            # 擇一達成即開始收 RR

# ---------- 電池監測 ----------
[battery]
enable     = true               # 顯示電量
poll_s     = 15                 # 幾秒查一次（只在 idle 時讀）
low_pct    = 20                 # 低電量門檻（狀態列橘色）
critical_pct = 10               # 極低門檻（狀態列紅色 + 提示）
raw_min    = 511                # 生電量原始值（低電）
raw_max    = 645                # 生電量原始值（滿電）
set_device_threshold_pct = 10   # 告知板子在 ~10% 亮燈（可選）

# ---------- UI ----------
[ui]
window_title = "ECG 訊號擷取、濾波、演算與應用教學系統（教學版）"

# 字型（全域）
font_family = "Microsoft JhengHei UI"
font_size   = 11

# 視窗大小（擇一）
ecg_width  = 1280               # 建議寬
ecg_height = 400                # 建議高（≈ 3.2:1）
# 或者只給比例：當 height 未設且有 ecg_aspect 時，用 width / aspect 自動算出 height
ecg_aspect = 3.2

# 啟動行為
center_on_start = true          # 啟動置中
start_maximized = false         # 啟動即最大化（true 時優先於置中）

# 即時心跳（藍，不粗體）
rt_hr_color = "#2962FF"
rt_hr_size  = 16
rt_hr_bold  = false

# 穩定心跳（紅、粗體）
stable_hr_color = "#D32F2F"
stable_hr_size  = 20
stable_hr_bold  = true

# 狀態列 / 工具列
status_text_color   = "#616161"
toolbar_button_bold = true

# pyqtgraph 軸標題（選配）
plot_label_color = "#90A4AE"
axis_label_size  = "12pt"

# ---------- 受試者欄位預設（啟動時自動帶入；僅示範用） ----------
[subject_defaults]
name = ""
age  = ""
sex  = "男"                     # 請用「男」/「女」以符合現有 main.py 的判斷
