# =========================================
# config.toml — ECG App 設定檔（含中文註解）
# 讀取位置：專案根目錄 /config.toml
# 注意：同一段落內（根層、[plot]、[filter]）每個鍵只能出現一次
# =========================================

# ---------- 裝置 / 一般設定 ----------
sampling_rate = 1000            # 取樣率(Hz)。BITalino 常用 1000；若改成 100、250 也可，但須與裝置一致
analog_channels = [1]           # 使用的類比通道索引（以 A1=0, A2=1, A3=2, ... 為準）
                                # 例：ECG 接在 A2 → 設為 [1]；若同時讀多通道可設如 [1, 2]
preferred_mac = ""              # （選用）BLE 自動連線時優先使用的 MAC（例："98:D3:31:xx:xx:xx"）
                                # 留空表示不指定，會由自動掃描決定（需安裝 bleak）
# address = ""                    # （選用）有線/指定位址（如 COM port "COM5" 或特定藍牙位址）。通常留空即可
# address = "COM16"             # CUST 8F 研究室 PC
address = "COM5"                # HOME Book Room PC

# ---------- 繪圖 / 展示 ----------
[plot]
seconds = 10                    # 畫面時間窗（秒），滑動顯示最近 N 秒資料
chunk = 100                     # 單批讀取/處理樣本數（與裝置 read(chunk) 對應）。1000Hz 時 100=每 0.1 秒更新
gain  = 1.5                     # 顯示增益（僅影響波形高低視覺，不改變數據值）

# ---------- 濾波（即時、串流友善） ----------
[filter]
enable = true                   # 是否啟用濾波；教學時可切換 true/false 對比原始與濾波後波形
band = [0.5, 25.0]              # 帶通頻帶(Hz)：0.5~25 可去除基線漂移與高頻肌電雜訊
notch = 60.0                    # 工頻陷波(Hz)：台灣 60；若干擾不明顯可改 0 停用（0=不做陷波）
order = 4                       # Butterworth 階數（2~4 常見；更陡可 6，但即時延遲與響應會變）
q = 30.0                        # 陷波 Q 值（20~50 常用；數值越大帶寬越窄）


[subject_defaults]
name = "林測試"
age  = 62
sex  = "男"   # 可填 "男" 或 "女"

[battery]
enable = true          # 顯示電量監測
poll_s = 15            # 幾秒查一次
low_pct = 20           # 低電量門檻（狀態列橘色）
critical_pct = 10      # 極低門檻（狀態列紅色與提示）

# 原始 battery 數值的線性映射（不同批次可微調）
raw_min = 511          # 低電（約 0~1%）
raw_max = 645          # 滿電（約 99%）
set_device_threshold_pct = 10   # 告知板子在 ~10% 時點紅燈（可選）

# ====== 教學備註 ======
# 1) 若未安裝 scipy，程式會自動改用內建「簡化濾波」（仍可即時運作）。
# 2) 若波形不像 ECG，請確認：
#    - 電極貼附位置與導線擺放
#    - analog_channels 是否對應你的實際接線（A1=0, A2=1, ...）
#    - preferred_mac / address 是否需要（若使用自動連線需安裝 bleak、pyserial）
# 3) notch 建議先依環境實測決定是否開啟；優先改善接地與布線，再依需要開陷波。
# 4) 本軟體用於研究/教學，不屬於醫療診斷。

